import { sql } from 'drizzle-orm';
import { sqliteTable, text, integer, real, index } from 'drizzle-orm/sqlite-core';
export const tenants = sqliteTable('tenants', {
  id: text('id').primaryKey(),
  name: text('name'),
  status: text('status').default('active').notNull(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (table) => [index('idx_tenants_status').on(table.status)]);
export const oracleDocuments = sqliteTable('oracle_documents', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').default('default').notNull().references(() => tenants.id),
  type: text('type').notNull(),
  sourceFile: text('source_file').notNull(),
  concepts: text('concepts').notNull(),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
  indexedAt: integer('indexed_at').notNull(),
  validTime: integer('valid_time').default(sql`null`),
  supersededBy: text('superseded_by'),
  supersededAt: integer('superseded_at'),
  supersededReason: text('superseded_reason'),
  origin: text('origin'),
  project: text('project'),
  createdBy: text('created_by'),
  usageCount: integer('usage_count').default(0).notNull(),
  lastAccessedAt: integer('last_accessed_at'),
}, (table) => [
  index('idx_source').on(table.sourceFile),
  index('idx_type').on(table.type),
  index('idx_superseded').on(table.supersededBy),
  index('idx_documents_tenant_superseded').on(table.tenantId, table.supersededBy),
  index('idx_origin').on(table.origin),
  index('idx_project').on(table.project),
  index('idx_documents_tenant').on(table.tenantId),
  index('idx_documents_usage_heat').on(table.usageCount, table.lastAccessedAt),
  index('idx_documents_tenant_type_active_updated').on(table.tenantId, table.type, table.supersededAt, table.updatedAt),
  index('idx_documents_tenant_valid_time').on(table.tenantId, table.validTime),
]);
export const oracleFts = sqliteTable('oracle_fts', { id: text('id'), content: text('content'), concepts: text('concepts') });
export const oracleEntityLinks = sqliteTable('oracle_entity_links', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').default('default').notNull().references(() => tenants.id),
  documentId: text('document_id').notNull().references(() => oracleDocuments.id, { onDelete: 'cascade' }),
  entity: text('entity').notNull(), entityKey: text('entity_key').notNull(),
  weight: integer('weight').default(1).notNull(),
  createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [
  index('idx_entity_links_tenant_key').on(table.tenantId, table.entityKey),
  index('idx_entity_links_tenant_doc').on(table.tenantId, table.documentId),
]);
export const oraclePointerIndex = sqliteTable('oracle_pointer_index', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').default('default').notNull().references(() => tenants.id),
  kind: text('kind').notNull(), key: text('key').notNull(),
  docIds: text('doc_ids').default('[]').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (table) => [
  index('idx_pointer_tenant_kind_key').on(table.tenantId, table.kind, table.key),
  index('idx_pointer_tenant_updated').on(table.tenantId, table.updatedAt),
]);
export const oracleMemories = sqliteTable('oracle_memories', {
  id: text('id').primaryKey(),
  tenantId: text('tenant_id').default('default').notNull(),
  content: text('content').notNull(),
  title: text('title'),
  tags: text('tags').default('[]').notNull(),
  source: text('source'),
  validFrom: integer('valid_from'),
  validTo: integer('valid_to'),
  supersededBy: text('superseded_by'), supersededAt: integer('superseded_at'), supersededReason: text('superseded_reason'),
  tier: text('tier').default('warm').notNull(), heatScore: real('heat_score').default(0).notNull(),
  usageCount: integer('usage_count').default(0).notNull(), lastAccessedAt: integer('last_accessed_at'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (table) => [
  index('idx_memory_created').on(table.createdAt),
  index('idx_memory_title').on(table.title),
  index('idx_memory_source').on(table.source),
  index('idx_memory_tenant_created').on(table.tenantId, table.createdAt),
  index('idx_memory_tenant_valid_time').on(table.tenantId, table.validFrom, table.validTo),
  index('idx_memory_tenant_tier_heat').on(table.tenantId, table.tier, table.heatScore),
]);
export const indexingStatus = sqliteTable('indexing_status', {
  id: integer('id').primaryKey(),
  isIndexing: integer('is_indexing').default(0).notNull(),
  progressCurrent: integer('progress_current').default(0),
  progressTotal: integer('progress_total').default(0),
  startedAt: integer('started_at'),
  completedAt: integer('completed_at'),
  error: text('error'),
  repoRoot: text('repo_root'),
});
export const indexingJobs = sqliteTable('indexing_jobs', {
  id: text('id').primaryKey(),
  docId: text('doc_id').notNull(),
  modelKey: text('model_key').notNull(),
  collection: text('collection').notNull(),
  status: text('status').default('pending').notNull(),
  attempts: integer('attempts').default(0).notNull(),
  createdAt: integer('created_at').default(sql`(strftime('%s','now')*1000)`).notNull(),
  claimedAt: integer('claimed_at'),
  finishedAt: integer('finished_at'),
  error: text('error'),
});
export const vectorIndexManifest = sqliteTable('vector_index_manifest', {
  id: text('id').primaryKey(), chunkId: text('chunk_id').notNull(),
  sourceFile: text('source_file').notNull(), modelKey: text('model_key').notNull(),
  contentHash: text('content_hash').notNull(),
  updatedAt: integer('updated_at').notNull(), indexedAt: integer('indexed_at').notNull(),
}, (table) => [
  index('idx_vector_manifest_model_hash').on(table.modelKey, table.contentHash),
  index('idx_vector_manifest_source').on(table.sourceFile),
]);
export const searchLog = sqliteTable('search_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  query: text('query').notNull(),
  tenantId: text('tenant_id').default('default').notNull(),
  type: text('type'),
  mode: text('mode'),
  resultsCount: integer('results_count'),
  searchTimeMs: integer('search_time_ms'),
  createdAt: integer('created_at').notNull(),
  project: text('project'),
  results: text('results'),
}, (table) => [
  index('idx_search_project').on(table.project),
  index('idx_search_tenant').on(table.tenantId),
  index('idx_search_created').on(table.createdAt),
  index('idx_search_tenant_created').on(table.tenantId, table.createdAt),
]);
export const consultLog = sqliteTable('consult_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  decision: text('decision').notNull(),
  context: text('context'),
  principlesFound: integer('principles_found').notNull(),
  patternsFound: integer('patterns_found').notNull(),
  guidance: text('guidance').notNull(),
  createdAt: integer('created_at').notNull(),
  project: text('project'),
}, (table) => [
  index('idx_consult_project').on(table.project),
  index('idx_consult_created').on(table.createdAt),
]);
export const learnLog = sqliteTable('learn_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  documentId: text('document_id').notNull(),
  tenantId: text('tenant_id').default('default').notNull(),
  patternPreview: text('pattern_preview'),
  source: text('source'),
  concepts: text('concepts'), // JSON array
  createdAt: integer('created_at').notNull(),
  project: text('project'),
}, (table) => [
  index('idx_learn_project').on(table.project),
  index('idx_learn_tenant').on(table.tenantId),
  index('idx_learn_created').on(table.createdAt),
]);
export const documentAccess = sqliteTable('document_access', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  documentId: text('document_id').notNull(),
  tenantId: text('tenant_id').default('default').notNull(),
  accessType: text('access_type'),
  createdAt: integer('created_at').notNull(),
  project: text('project'),
}, (table) => [
  index('idx_access_project').on(table.project),
  index('idx_access_tenant').on(table.tenantId),
  index('idx_access_created').on(table.createdAt),
  index('idx_access_doc').on(table.documentId),
]);
export const forumThreads = sqliteTable('forum_threads', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  title: text('title').notNull(),
  tenantId: text('tenant_id').default('default').notNull(),
  createdBy: text('created_by').default('human'),
  status: text('status').default('active'),
  issueUrl: text('issue_url'),
  issueNumber: integer('issue_number'),
  project: text('project'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
  syncedAt: integer('synced_at'),
}, (table) => [
  index('idx_thread_status').on(table.status),
  index('idx_thread_project').on(table.project),
  index('idx_thread_tenant').on(table.tenantId),
  index('idx_thread_created').on(table.createdAt),
  index('idx_thread_tenant_status_updated').on(table.tenantId, table.status, table.updatedAt),
]);
export const forumMessages = sqliteTable('forum_messages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  threadId: integer('thread_id').notNull().references(() => forumThreads.id),
  role: text('role').notNull(),
  content: text('content').notNull(),
  author: text('author'),
  principlesFound: integer('principles_found'),
  patternsFound: integer('patterns_found'),
  searchQuery: text('search_query'),
  commentId: integer('comment_id'),
  createdAt: integer('created_at').notNull(),
}, (table) => [
  index('idx_message_thread').on(table.threadId),
  index('idx_message_role').on(table.role),
  index('idx_message_created').on(table.createdAt),
]);
export const traceLog = sqliteTable('trace_log', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  traceId: text('trace_id').unique().notNull(),
  tenantId: text('tenant_id').default('default').notNull(),
  query: text('query').notNull(),
  queryType: text('query_type').default('general'),
  foundFiles: text('found_files'),
  foundCommits: text('found_commits'),
  foundIssues: text('found_issues'),
  foundRetrospectives: text('found_retrospectives'),
  foundLearnings: text('found_learnings'),
  foundResonance: text('found_resonance'),
  fileCount: integer('file_count').default(0),
  commitCount: integer('commit_count').default(0),
  issueCount: integer('issue_count').default(0),
  depth: integer('depth').default(0),
  parentTraceId: text('parent_trace_id'),
  childTraceIds: text('child_trace_ids').default('[]'),
  prevTraceId: text('prev_trace_id'),
  nextTraceId: text('next_trace_id'),
  project: text('project'),
  scope: text('scope').default('project'),
  sessionId: text('session_id'),
  agentCount: integer('agent_count').default(1),
  durationMs: integer('duration_ms'),
  status: text('status').default('raw'),
  awakening: text('awakening'),
  distilledToId: text('distilled_to_id'),
  distilledAt: integer('distilled_at'),
  createdAt: integer('created_at').notNull(),
  updatedAt: integer('updated_at').notNull(),
}, (table) => [
  index('idx_trace_query').on(table.query),
  index('idx_trace_project').on(table.project),
  index('idx_trace_tenant').on(table.tenantId),
  index('idx_trace_status').on(table.status),
  index('idx_trace_parent').on(table.parentTraceId),
  index('idx_trace_prev').on(table.prevTraceId),
  index('idx_trace_next').on(table.nextTraceId),
  index('idx_trace_created').on(table.createdAt),
]);
export { exportJobs } from './export-schema.ts';
export { activityLog, menuItems, schedule, settings, supersedeLog } from './logistics-schema.ts';
export { assertSqliteIdentifier, oracleVectorDocuments, sqliteVecEmbeddingsTable, sqliteVecMetadataTable, vectorDocumentsTable } from './vector-schema.ts';
