import { existsSync, readdirSync, readFileSync, statSync } from 'fs';
import { basename, extname, join, relative } from 'path';
import { REPO_ROOT } from '../config.ts';
import { handleSearch } from '../server/handlers.ts';
import { nodeName } from './identity.ts';
export interface PeerSearchResult { id: string; score: number; title: string; snippet: string; }
function capLimit(limit: unknown) { const n = Number(limit ?? 10); return Math.min(50, Math.max(1, Number.isFinite(n) ? Math.trunc(n) : 10)); }
function walk(dir: string, out: string[] = []): string[] { if (!existsSync(dir)) return out; for (const ent of readdirSync(dir, { withFileTypes: true })) { if (['node_modules','.git','.omx','agents'].includes(ent.name)) continue; const p = join(dir, ent.name); if (ent.isDirectory()) walk(p, out); else if (/\.(md|mdx|txt)$/i.test(ent.name)) out.push(p); } return out; }
function titleFrom(path: string, text: string) { return text.match(/^#\s+(.+)$/m)?.[1]?.trim() || basename(path, extname(path)); }
function snippet(text: string, q: string) { const idx = text.toLowerCase().indexOf(q.toLowerCase()); const start = Math.max(0, idx < 0 ? 0 : idx - 80); return text.slice(start, start + 240).replace(/\s+/g, ' ').trim(); }
async function dbSearch(query: string, limit: number): Promise<PeerSearchResult[]> { const r = await handleSearch(query, 'all', limit, 0, 'hybrid'); return (r.results ?? []).slice(0, limit).map((x: any, i: number) => ({ id: String(x.id), score: typeof x.score === 'number' ? x.score : 1 / (i + 1), title: x.source_file ? basename(String(x.source_file)) : String(x.type ?? x.id), snippet: String(x.content ?? '').replace(/\s+/g, ' ').slice(0, 240) })); }
function fsSearch(query: string, limit: number): PeerSearchResult[] { const q = query.toLowerCase(); const results: PeerSearchResult[] = []; for (const file of walk(REPO_ROOT)) { const text = readFileSync(file, 'utf8'); const idx = text.toLowerCase().indexOf(q); if (idx < 0) continue; results.push({ id: relative(REPO_ROOT, file), score: 1, title: titleFrom(file, text), snippet: snippet(text, query) }); if (results.length >= limit) break; } return results.sort((a,b) => statSync(join(REPO_ROOT,b.id)).mtimeMs - statSync(join(REPO_ROOT,a.id)).mtimeMs); }
export async function peerSearch(input: { query?: unknown; q?: unknown; limit?: unknown }) { const q = String(input.query ?? input.q ?? '').trim(); const limit = capLimit(input.limit); if (!q) return { node: nodeName(), oracle: 'arra', results: [] as PeerSearchResult[] }; let results: PeerSearchResult[] = []; try { results = await dbSearch(q, limit); } catch {} if (!results.length) results = fsSearch(q, limit); return { node: nodeName(), oracle: 'arra', query: q, results: results.slice(0, limit) }; }
