export type McpRestMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE';
export type McpRestBodyMode = 'args' | 'thread-message' | 'thread-status' | 'trace-link' | 'trace-distill';

export type McpRestQueryBinding = Readonly<{
  arg: string;
  param: string;
}>;

export type McpRestStaticQuery = Readonly<{
  param: string;
  value: string;
}>;

type BaseMcpRestEntry = Readonly<{
  name: string;
  remoteable: boolean;
  notes?: string;
}>;

export type RemoteableMcpRestEntry = BaseMcpRestEntry & Readonly<{
  remoteable: true;
  method: McpRestMethod;
  path: string;
  pathParams?: readonly string[];
  pathVariants?: readonly string[];
  query?: readonly McpRestQueryBinding[];
  staticQuery?: readonly McpRestStaticQuery[];
  body?: McpRestBodyMode;
}>;

export type LocalOnlyMcpRestEntry = BaseMcpRestEntry & Readonly<{
  remoteable: false;
  reason: string;
}>;

export type McpRestMapEntry = RemoteableMcpRestEntry | LocalOnlyMcpRestEntry;

const searchQuery = [
  { arg: 'query', param: 'q' },
  { arg: 'type', param: 'type' },
  { arg: 'limit', param: 'limit' },
  { arg: 'offset', param: 'offset' },
  { arg: 'mode', param: 'mode' },
  { arg: 'retrieval', param: 'retrieval' },
  { arg: 'project', param: 'project' },
  { arg: 'cwd', param: 'cwd' },
  { arg: 'model', param: 'model' },
] as const;

const pagingQuery = [
  { arg: 'type', param: 'type' },
  { arg: 'limit', param: 'limit' },
  { arg: 'offset', param: 'offset' },
] as const;

const traceListQuery = [
  { arg: 'query', param: 'query' },
  { arg: 'status', param: 'status' },
  { arg: 'project', param: 'project' },
  { arg: 'limit', param: 'limit' },
  { arg: 'offset', param: 'offset' },
] as const;

const mcpRestMapEntries = [
  { name: '____IMPORTANT', remoteable: false, reason: 'guide response is generated by each MCP host' },
  { name: 'oracle_recap', remoteable: false, reason: 'wake-up recap is generated from embedded MCP context' },
  { name: 'oracle_search', remoteable: true, method: 'GET', path: '/api/search', query: searchQuery },
  { name: 'oracle_search_chain', remoteable: true, method: 'POST', path: '/api/v1/search/chain', body: 'args' },
  { name: 'oracle_read', remoteable: true, method: 'GET', path: '/api/read', query: [{ arg: 'file', param: 'file' }, { arg: 'id', param: 'id' }] },
  { name: 'oracle_learn', remoteable: true, method: 'POST', path: '/api/learn', body: 'args' },
  { name: 'oracle_list', remoteable: true, method: 'GET', path: '/api/list', query: pagingQuery, staticQuery: [{ param: 'group', value: 'false' }] },
  { name: 'oracle_stats', remoteable: true, method: 'GET', path: '/api/stats' },
  { name: 'oracle_concepts', remoteable: true, method: 'GET', path: '/api/concepts', query: [{ arg: 'type', param: 'type' }, { arg: 'limit', param: 'limit' }] },
  { name: 'oracle_supersede', remoteable: true, method: 'POST', path: '/api/supersede/document', body: 'args' },
  { name: 'oracle_research_note', remoteable: true, method: 'POST', path: '/api/research/note', body: 'args' },
  { name: 'oracle_handoff', remoteable: true, method: 'POST', path: '/api/handoff', body: 'args' },
  { name: 'oracle_inbox', remoteable: true, method: 'GET', path: '/api/inbox', query: pagingQuery },
  { name: 'oracle_thread', remoteable: true, method: 'POST', path: '/api/thread', body: 'thread-message' },
  { name: 'oracle_threads', remoteable: true, method: 'GET', path: '/api/threads', query: [{ arg: 'status', param: 'status' }, { arg: 'limit', param: 'limit' }, { arg: 'offset', param: 'offset' }] },
  { name: 'oracle_thread_read', remoteable: true, method: 'GET', path: '/api/thread/:threadId', pathParams: ['threadId'] },
  { name: 'oracle_thread_update', remoteable: true, method: 'PATCH', path: '/api/thread/:threadId/status', pathParams: ['threadId'], body: 'thread-status' },
  { name: 'oracle_profile', remoteable: true, method: 'GET', path: '/api/oracles/profiles/:id?', pathParams: ['id'] },
  { name: 'oracle_trace', remoteable: true, method: 'POST', path: '/api/traces', body: 'args' },
  { name: 'oracle_trace_list', remoteable: true, method: 'GET', path: '/api/traces', query: traceListQuery },
  { name: 'oracle_trace_get', remoteable: true, method: 'GET', path: '/api/traces/:traceId', pathParams: ['traceId'], pathVariants: ['/api/traces/:traceId/chain'] },
  { name: 'oracle_trace_link', remoteable: true, method: 'POST', path: '/api/traces/:prevTraceId/link', pathParams: ['prevTraceId'], body: 'trace-link' },
  { name: 'oracle_trace_unlink', remoteable: true, method: 'DELETE', path: '/api/traces/:traceId/link', pathParams: ['traceId'], query: [{ arg: 'direction', param: 'direction' }] },
  { name: 'oracle_trace_chain', remoteable: true, method: 'GET', path: '/api/traces/:traceId/linked-chain', pathParams: ['traceId'] },
  { name: 'oracle_trace_distill', remoteable: true, method: 'POST', path: '/api/traces/:traceId/distill', pathParams: ['traceId'], body: 'trace-distill' },
  { name: 'oracle_reflect', remoteable: true, method: 'GET', path: '/api/reflect' },
  { name: 'oracle_verify', remoteable: true, method: 'POST', path: '/api/verify', body: 'args' },
  { name: 'oracle_mcp_list_tools', remoteable: false, reason: 'MCP-in helper; HTTP clients use /api/mcp/tools directly' },
  { name: 'oracle_mcp_call', remoteable: false, reason: 'MCP-in helper; proxying it would recurse through MCP' },
] as const satisfies readonly McpRestMapEntry[];

export type McpRestToolName = typeof mcpRestMapEntries[number]['name'];
export const mcpRestMap: readonly McpRestMapEntry[] = mcpRestMapEntries;
export const remoteableMcpRestMap = mcpRestMap.filter((entry): entry is RemoteableMcpRestEntry => entry.remoteable);
export const mcpRestMapByName = new Map<string, McpRestMapEntry>(mcpRestMap.map((entry) => [entry.name, entry]));
